### ISSUE TITLE
Bug Report: Reliably Dropping Inputs and Having One Press Count for Multiple Notes

### ISSUE THREAD

**Issue by PneumaAsh** [KadeArchive/Kade-Engine#1030]
**Please check for duplicates, similar issues or closed issues with the same problem**

Another person talking about inputs being carried over to multiple notes may have been experiencing the same issue as me, but in my case it makes my WiP mod nearly unplayable. A similar issue existed in 1.5.3, but it wasn't nearly as bad as it is now

**What operating system are you using?**

Windows x86, specifically Pro if that matters

**What version of the game are you using?**

1.5.4, I just updated from 1.5.3

**Have you identified any steps to reproduce the bug?**

Playing the song multiple times

**Please describe your issue.**

I seem to be having 2 issues. 
1. The same as another user's bug report, holding notes will make consecutive notes count as bads
2. I am dropping inputs consistently at certain parts

During sections with consecutive hands and quad holds specifically I am experiencing consistently dropped inputs. As you'll see in the first provided video, I'm also at times dropping inputs when only hitting 1 or 2 at a time (spaced very far apart). The second video will be a recording I took while on version 1.4.1 of Kade Engine, playing the same map, to demonstrate just how bad this issue has gotten

Video 1, taken on version 1.5.4 of Kade Engine - the 2nd issue is most prevalent from 2:30 or so to the end of the video
https://www.youtube.com/watch?v=lwUCMIeVAZc

Video 2, taken on version 1.4.1 of Kade Engine - the only issue here is a lag spike, which I believe came from having the game open for too long
https://www.youtube.com/watch?v=1pmUg-P3nUg

I've also been having a third issue. I know how to work around it most times, but it can be annoying. When I go for quad holds, sometimes the game will just not register that I hit all the notes. The workaround is to press the keys early on purpose, but that causes me to lose accuracy. It's also not always a reliable solution, especially in the parts in my own mod where I have consecutive quad holds, because it can be hard to remember to dodge that problem. This isn't a **MASSIVE** problem, it just is there

**Comment by isakube** [comment]
this is why i never update my mods lol

**Comment by Kade-github** [comment]
1.5.4 was tested and confirmed to have fixed this, really weird that it's happening to you. 1.5.4 was tested on dense maps and even maps with consecutive jump holds. 

Anyways, I'm confused since I don't drop anything on quads. What are your keybinds/specs?

https://user-images.githubusercontent.com/26305836/123484561-6847c000-d5bd-11eb-8198-bb6522daa1cd.mp4

200 BPM:

https://user-images.githubusercontent.com/26305836/123486482-f83b3900-d5c0-11eb-9ec3-95d06ffa737f.mp4



Edit: can you also provide the file that's giving you this issue?

**Comment by ItzFireable** [comment]
No drops over here. Are you sure you ported your mod properly?

https://user-images.githubusercontent.com/38793386/123487103-fc457600-d615-11eb-93ee-4647b2c7340c.mp4

**Comment by poco0317** [comment]
hey i analyzed the evidence videos here and this is working as intended due to stacked notes

in the "working" video you have the combo increase for a single tap going from 61 to 63 (around 2:16)
in the "broken" video you have the combo increase by 1 as intended and the stacked note goes by and counts as a miss

fix ur shit

**Comment by Kade-github** [comment]
Alright, so I'm going to consider this solved. We did some testing and found out your chart is fucked, you have stacked notes in your quads which leads to you hitting all of them and missing one since the game processes it as 4 notes instead of 5, which is intended since 1 key press = one judgment (no double judgments)

anyways this should be impossible now due to this commit. 
https://github.com/KadeDev/Kade-Engine/commit/5105c95929a48aa7fc62b2f5ac1be95670760593
