### ISSUE TITLE
polymod? 

### ISSUE THREAD

**Issue by fowure** [KadeArchive/Kade-Engine#1062]
it says "source/PlayState.hx:3379: characters 17-32 : Class<webm.WebmPlayer> has no field SKIP_STEP_LIMIT
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/format/XMLMerge.hx:189: characters 10-23 : Warning : This typedef is deprecated in favor of haxe.xml.Access
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/format/XMLMerge.hx:189: characters 30-43 : Warning : This typedef is deprecated in favor of haxe.xml.Access" when i type lime test windows, i have polymod downloaded and everything

**Comment by ACardboardBox1** [comment]
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/format/XMLMerge.hx:189: characters 10-23 : Warning : This typedef is deprecated in favor of haxe.xml.Access
C:/HaxeToolkit/haxe/lib/polymod/git/polymod/format/XMLMerge.hx:189: characters 30-43 : Warning : This typedef is deprecated in favor of haxe.xml.Access" these are deprecations. they dont do nothing.
source/PlayState.hx:3379: characters 17-32 : Class<webm.WebmPlayer> has no field SKIP_STEP_LIMIT might be a error though. otherwise, duplicate of #1059.

**Comment by isakube** [comment]
polymod isnt even implemented properly, i would make a pr to remove the initilization but kade probably doesnt want me to do that

**Comment by epicbobmanbob** [comment]
its a warning. you dont need to care about that. the game still works fine.

**Comment by Kade-github** [comment]
"source/PlayState.hx:3379: characters 17-32 : Class<webm.WebmPlayer> has no field SKIP_STEP_LIMIT" read FUCKING BUILDING.MD.

https://github.com/KadeDev/Kade-Engine/blob/stable/docs/building.md
https://github.com/KadeDev/Kade-Engine/blob/stable/docs/building.md
https://github.com/KadeDev/Kade-Engine/blob/stable/docs/building.md
https://github.com/KadeDev/Kade-Engine/blob/stable/docs/building.md
https://github.com/KadeDev/Kade-Engine/blob/stable/docs/building.md
