### ISSUE TITLE
Bug Report: Song crashing when hovered over in freeplay

### ISSUE THREAD

**Issue by XaraKuma** [KadeArchive/Kade-Engine#1425]
I tried adding a song to the Freeplay system and it keeps crashing when hovered over. I even tried it on a new downloaded kade engine folder without any modification of the code to see if it's anything related to the code I changed. still crashes. I've put "Breaking Point:spirit:7" in the freeplaysonglist.txt. The data folder, chart JSON, and song folder are named "breaking-point". I'm not sure if I'm probably missing any steps or it's the engine bug. I also have the "Inst" and "Voices" files named correctly in the song folder with both versions of mp3 and Ogg files inside.

**Comment by tofu111456** [comment]
same that also happened to me ;3;

**Comment by naelsun** [comment]
also happening to me :/

**Comment by Kade-github** [comment]
did you add the easy normal and hard diffs (if you don't have them copy and paste the original diff and rename them.)

Ke requires all of the diffs to be there. This is more or less not a bug, and more user error. Though I can't blame you since it doesn't tell you this, which has been clarified in the latest commits.
