### ISSUE TITLE
Bug Report: Charting is a mess :C (BF doesn't sing his chart)

### ISSUE THREAD

**Issue by ChisanaKuma** [KadeArchive/Kade-Engine#1501]
Hey! I was making my mod, but i notice that the charting is making some weird stuff;
In the editor everything is alright, but at playing, the P2 sing most of the notes; i dont get it; also, if i change the camera point only to BF; P2 plays the first and BF SOME of the final notes; 
i could not find some similar anywhere; why this happen??

i attach some images; the first one is the editor and the second at play mode; is the same part of the song.
Please help me :C i wanna do it right.
![image](https://user-images.githubusercontent.com/88127042/127433377-0b92de20-7c98-4fa3-bf9c-132fb6aabdf0.png)

![image](https://user-images.githubusercontent.com/88127042/127433542-bb82e496-285e-47dd-adbc-0eb7b76c10ad.png)

**This is my twitter --> www.twitter.com/chisanakuma315**

**Comment by KadeDev** [comment]
So the icons on the right show who is singing that section of notes, if bf's icon is on the left and you put notes on the right. The opponent will sing them. And vice versa. The fix is to move these to the left side.
![image](https://user-images.githubusercontent.com/26305836/127443343-97fa45d5-03a2-4202-bb5e-0d5406603c96.png)

**Comment by Kade-github** [comment]
So the icons on the right show who is singing that section of notes, if bf's icon is on the left and you put notes on the right. The opponent will sing them. And vice versa. The fix is to move these to the left side.
![image](https://user-images.githubusercontent.com/26305836/127443406-7d8b9158-5ae9-49d3-87ac-65a3b715dbcd.png)

**Comment by ChisanaKuma** [comment]
Okey, i'll do that.
But i dont like it :c
I made the camera changes first to fit the song i hope this will change or maybe an option to disable it
