### ISSUE TITLE
A way to reset the appearance

### ISSUE THREAD

**Issue by Blantados** [KadeArchive/Kade-Engine#166]
I've moved the sick text once in that menu. I could never get it back to the original position.

**Comment by Jaduplex** [comment]
good idea. might try to do this

**Comment by puyoxyz** [comment]
i know technically https://github.com/KadeDev/Kade-Engine/issues/339 is a duplicate of THIS and not the other way around but https://github.com/KadeDev/Kade-Engine/issues/339 is a bit more just a general improve customize gameplay so like closing this yeah because this is included in https://github.com/KadeDev/Kade-Engine/issues/339
