### ISSUE TITLE
Bug Report: Can't change the BPM of songs in the charter

### ISSUE THREAD

**Issue by CarsonKompon** [KadeArchive/Kade-Engine#1757]
### If you are playing a downloaded version of the game, what operating system are you using?

Windows 10 64-bit

## What version of the game are you using? Look in the bottom left corner of the main menu.

1.6.2 - Full Release

## Please describe your issue. Provide extensive detail and images if possible.

If you go into a song and change it's Init BPM event to another value, you are no longer able to navigate through your chart with the scroll wheel or arrow keys. Pressing enter will load the song just fine, but pressing 7 to return to the charter will cause your game to crash.
 
I've made a video to more easily describe the issue: https://streamable.com/godpti

This is the console output upon crash:
```
source/ChartingState.hx:142: false
source/ChartingState.hx:531: 640
source/ChartingState.hx:535: height of 636
source/Conductor.hx:68: new BPM map BUDDY []
source/ChartingState.hx:227: goin
source/ChartingState.hx:2873: RECALCULATING SECTION TIMES
source/ChartingState.hx:272: Song length in MS: 75590
```

**Comment by Kade-github** [comment]
Very easy fix, the reason why this happens is the saved typed doesn't actually get declared as any "valid type" which means if you load into the song and then save the bpm change event, it will be nothing because the saved type is nothing. a fix is to simply click on the bpm change type drop down and then click save again. A little work around until a bug fix is pushed.

https://github.com/KadeDev/Kade-Engine/commit/17281d85cd492b570b3c8bcba62199a8996e492d
