### ISSUE TITLE
Bug Report: Game Crashes upon attempting to play an imported JSON

### ISSUE THREAD

**Issue by Manicies** [KadeArchive/Kade-Engine#1813]
I'm using the Kade engine 1.16.1, attempting to import a song from another kade engine mod, though it is from kade engine 1.4.2, which I understand is quite outdated. The song works just fine if I just import the song without a JSON, or even if I just create my own with the song. Is it crashing due to the 1.4.2 JSON being out of date, and if so, is there anything I can do to fix it? 

The weirdest part is, in the debug menu, the JSON works just fine. I can mess around with the charting, and it's all correct and accurate. It just crashes when I attempt to play the song using the imported JSON.

**Comment by KlutchDj** [comment]
its not the json issue. youd need to rename the song name inside the json file to be playable . i just tested this out as well with a 1.4.2 json and all i know is that you have to rename the json and rename the song inside the json for it to work. otherwise im just blind and dont know what im talking about. close this once you have resolved the crashing issue

**Comment by Manicies** [comment]
> its not the json issue. youd need to rename the song name inside the json file to be playable . i just tested this out as well with a 1.4.2 json and all i know is that you have to rename the json and rename the song inside the json for it to work. otherwise im just blind and dont know what im talking about. close this once you have resolved the crashing issue

You absolute legend. That was it. Lifesaver. I could kiss you.
