### ISSUE TITLE
Bug Report:  The music doesn't stop

### ISSUE THREAD

**Issue by JustSimonDiamond** [KadeArchive/Kade-Engine#2102]
I usually have lag problems with my PC, and to play Friday Night Funkin in a better way I use Kade Engine, well, every time I start a new week I have to pause the game to make it not close, the problem is that when I pause the game, the music simply continues, it does not stop, and it causes the game to be ruined, because the chart also runs, even if it is paused. Another thing with this bug is that it can be done if you pause the game too many times, I don't know how many times exactly, but it is achieved.

Kade Engine Version: 1.7 Release

My PC:

Windows 10 Pro x64
Intel Celeron CPU N2805 1.46GHz
2GB RAM DDR3
300GB ROM HDD
Intel HD Graphics

**Comment by NK-523** [comment]
I've been charting a finger breaker song for almost a day now, and almost every time I pause this happens, and if you compile it in debug mode and hit ` or \ it opens the console and if you close that it causes it to go even if paused, so I think it is caused by a song with a lot of notes. 
![image](https://user-images.githubusercontent.com/77185327/132024190-619ea3a0-1e3b-4d6f-9bb9-f2418bbd9f2e.png)
