### ISSUE TITLE
Bug Report: After the first song in my custom week the camera never moves

### ISSUE THREAD

**Issue by Unity123** [KadeArchive/Kade-Engine#2134]
### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.

Windows (`x86_64`)

## What version of the game are you using? Look in the bottom left corner of the main menu.

1.7

## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.

https://gamebanana.com/mods/319093
Download it.
Play past the first song.
The camera doesn't move until you open and close the chart editor.

## Please describe your issue. Provide extensive detail and images if possible.

See previous stuff

**Comment by NK-523** [comment]
have you tried building a debug build with `lime test windows -debug`

**Comment by NK-523** [comment]
might give you an error message in the console.

**Comment by KlutchDj** [comment]
dude uhh , have you tried switching camera sections in the chart editor ?

**Comment by Unity123** [comment]
Yes, I have tried both of those. The camera does move in freeplay and it used to move fine in story mode, but once I added dialogue past the first song the camera never even moved to point at the opponent. There are no error messages.

**Comment by brockeosaurus** [comment]
I'm actually having the same problem.
I have no idea what exactly is causing it or how to fix it.
My issue is even worse, my camera doesn't move AND whenever I have to play a note, it registers that I have the key pressed but it won't hit the arrow.
The camera moves for a few frames and then stops, which coincides with my char, bf and gf playing only one repeat of the idle animation before freezing as well. My char and bf will still play note animations, but the idle is still frozen.
I'm thinking it has to do with something in PlayState.hx, but I have no idea what because there is so much and I don't know a lot of haxe.
launching a debug build does not give an error message or anything.

Please help

Please
