### ISSUE TITLE
help!

### ISSUE THREAD

**Issue by jonjonhtml** [KadeArchive/Kade-Engine#2168]
hi! i am trying to code a mod to fnf
i added custom character and custom stage (with the code of dad's stage just with different file names)
it's compiling good without errors but whenever i open the week it opens the right song but with the default stage and dad's sprite 
i can switch to my custom character with the debug menu but i want it to be there by the start of the song  
but when i try to load the custom stage it just loading the same default stage again  
can you please help me with these 2 issues? 
(and don't tell me to replace the default stage png bc i need it

have a wonderful day!
jon

**Comment by G4merz** [comment]
check stage code
check the charting
check xml
check character code
check characterList.txt

**Comment by notmagniill** [comment]
> check stage code
> check the charting
> check xml
> check character code
> check characterList.txt

yes correct, first you gotta check the stage code, if it has the week 1 bg name, rename it to yours. then you also need to check the charting, who knows, maybe you put the wrong bg and character name. then check the character code, if you wrotten the wrong xml code (actually g4merz you don't really need to change the xml because it can only detect the upper wrotten file) on the character code the game wouldn't work. and lastly check characterList.txt because if you wrotten the same name with one of the character names, it would be original.

Have a nice day!!!
Magniill

**Comment by jonjonhtml** [comment]
hello! sorry to keep ya all waiting i managed to get my character as the default and also my stage but not as default  i checked in the jsons and there are no references to any stage and also my stage dosen't have xml  
can you tell me how to fix that? so the stage will be default?
have a wonderful day!
