### ISSUE TITLE
(bug) not registering hits when I hit my keys

### ISSUE THREAD

**Issue by axlylol** [KadeArchive/Kade-Engine#402]
i was trying to play dark sheep and i dragged into my kade engine then played it and my hits didnt register AT ALL and i didnt change any of the offset or safe note settings, then i thought it was just the mod but i checked another song and my hits still didnt register, any  ideas?

**Comment by Kade-github** [comment]
Are you using the right keys? do you have any programmers such as auto hotkey rebinding keys and you just forgot? Or smth else

**Comment by puyoxyz** [comment]
are you *sure* your safe frames are correct (10)? (did you check?) and are you hitting the keys that you have set in settings (i.e. hitting WASD if you set WASD in settings, hitting DFJK if you set DFJK in settings)? if both yes, does it work if you use the arrow keys?

**Comment by Bicren** [comment]
I can confirm that the bug is something with the engine, I tried playing "Mid masses fight" mod but some keys wont register the hits, and it shows that i am pressing it, but it wont register

The way I am playing however is, the left hand on the "A" & "S" keys, and the right hand on the "UP arrow" & "RIGHT arrow" keys

some mods are not even playable with that, I am currently making my own mod, but when i tested the chards it the keys wont register

**Comment by axlylol** [comment]
I changed my safe frames to 10, i guess that was the problem, it probably happened when I was trying to fix my settings due to the settings reset in the new version, thank you for the help! <3
