### ISSUE TITLE
Bug about health bar losses

### ISSUE THREAD

**Issue by Ihave0idea** [KadeArchive/Kade-Engine#430]
#### Please check for duplicates, similar issues or closed issues with the same problem, as well performing simple troubleshooting steps (such as deleting the export folder if it's an issue with compiling, reinstalling Kade Engine) before submitting an issue.

nope

### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.

macOS

## What version of the game are you using? Look in the bottom left corner of the main menu.
1.3

## Have you identified any steps to reproduce the bug? If so, please describe them below. Use images if possible.
No

## Please describe your issue. Provide extensive detail and images if possible.

It makes be lose everytime I lost 5 notes at once, I noticed you gain very little but when you miss a note you get pushed back VERY hard

**Comment by isakube** [comment]
why are you playing on 1.3, also this was probably fixed by now

**Comment by blackm1n** [comment]
> why are you playing on 1.3, also this was probably fixed by now

Probably because it's the last version that supports Old Input System? (though idfk why, since recent Kade Engine versions added "Ghost Tapping" and you can turn it off which is basically Old Input System)

**Comment by Kade-github** [comment]
> ghost tapping

Ghost Tapping is a feature that most people use to allow you to keep a rhythm in a game by tapping notes that don't exist, this is just a way that some people keep a metronome in their mind. 

Old Input was a bad way of describing it, and it has been changed to ghost tapping. Changing ghost tapping on or off in newer versions doesn't change the inputs, it changes how you can input notes. But otherwise nothing else.

To your question, the health drain was intentional. But has been moved down in recent builds.

A more in-depth explanation of how inputs are handled:

Inputs are handled based on the exact timing of your note presses. There exists an entire hit window of 166 milliseconds to hit something. 
Kade Engine offers the ability to customize your gameplay so you get rewarded for how accurate you are on a giant scale (accurate accuracy, an option for accuracy).

Or based on each note (complex accuracy, another option that factors in your difference between hitting the notes. For example, you hit a note at 36ms, that would be a sick since the default sick window is 45ms. it would also factor into your accuracy using the Wife3 function described [here](https://github.com/KadeDev/Kade-Engine/blob/master/source/EtternaFunctions.hx#L63))

Generally, the idea of the input is to reward higher skill plays to allow people to overachieve and have a fair gameplay loop with the ability to customize it depending on their skill. In the options, you can change the hit windows to make them stricter or easier, depending on your play style or map choice.

I hope this is a good enough explanation for anyone who is lurking on this or anyone who wants to know anything about KE at all. I'm sure OP doesn't care in the slightest lol.

But this is more of a summary of what we do.

**Comment by Sebyal** [comment]
"Mental mind" :trollface:

**Comment by Kade-github** [comment]
> "Mental mind" :trollface:

imagine a mind in a mind :trollface:

**Comment by Ihave0idea** [comment]
OK
