### ISSUE TITLE
i want to make an fnf mod with kade engine but i use a chromebook to do stuff how would i make it

### ISSUE THREAD

**Issue by lemonsxeed** [KadeArchive/Kade-Engine#472]
i tried making one, the problem is the manifest because i had some json files and it wasnt listed in the manifest in the js and when i try to it shows an error how do i fix this

**Comment by puyoxyz** [comment]
What error?

**Comment by lemonsxeed** [comment]
Kade Engine.js:119014 [lime.utils.Assets] ERROR: There is no TEXT asset with an ID of "assets/data/megalo strike back/megalo strike back-hard.json"

**Comment by puyoxyz** [comment]
you can't have spaces in filename, rename file(s) to `megalo-strike-back-hard.json`, `megalo-strike-back.json`, etc, and use `megalo-strike-back` in the code

**Comment by lemonsxeed** [comment]
ah ok

**Comment by lemonsxeed** [comment]
let me try

**Comment by lemonsxeed** [comment]
still did not work

**Comment by puyoxyz** [comment]
what error now?

**Comment by lemonsxeed** [comment]
the same, i think it is because the manifest file in the js or something

**Comment by puyoxyz** [comment]
yeah, you forgot to edit it in the code

**Comment by lemonsxeed** [comment]
how would you do it and also i am using the html5

**Comment by puyoxyz** [comment]
...like you did the first time, but instead of putting `megalo strike back` put `megalo-strike-back`

**Comment by lemonsxeed** [comment]
i did not write the manifest file for the assets, i hate myself

**Comment by lemonsxeed** [comment]
how would i make them then

**Comment by lemonsxeed** [comment]
h

**Comment by dacixn** [comment]
i have a question, how do you test your html5 build on your chromebook? when i double click the html5 file it just shows a black screen for me, and if i try it with puyos nightly build it just shows the flixel loading screen but on 0%

**Comment by puyoxyz** [comment]
> i have a question, how do you test your html5 build on your chromebook? when i double click the html5 file it just shows a black screen for me, and if i try it with puyos nightly build it just shows the flixel loading screen but on 0%

in that case it's probably an issue with your browser (since it happens on the hosted builds too)

to help with your own builds not working: what are you using to build on chromebook? (crostini? termux? crouton?)

to figure out whats happening with hosted builds: can you open the dev tools (`ctrl+shift+i`) and send a screenshot of the console (*after* it gets stuck)?

**Comment by dacixn** [comment]
i'm using crostini

![image](https://user-images.githubusercontent.com/77625708/118402277-36931f00-b637-11eb-9266-edad47769cbc.png)
this is what it shows

**Comment by puyoxyz** [comment]
oh when you download it, it breaks, ok that makes sense i guess, anyways, make a separate issue for the thing where ur builds dont work

**Comment by dacixn** [comment]
it only does the thing shown on the screenshot when i try to load it up from my system, but if i upload it to itch.io it works fine

**Comment by puyoxyz** [comment]
then that's just a problem with chromeos being stupid; try doing `lime build html5` then `lime run html5`? i think that makes it start its own webserver (which would bypass chromeos' stupidity)? but idk? not sure? if that doesn't work make a [discussion](https://github.com/KadeDev/Kade-Engine/discussions) because this is an unrelated issue

**Comment by dacixn** [comment]
ok thank u
