### ISSUE TITLE
Bug Report: Song from week missing

### ISSUE THREAD

**Issue by SomeKindofGamer** [KadeArchive/Kade-Engine#508]
Every time I build the game the last song from the week is missing!
I don't know how to fix this

**Comment by isakube** [comment]
update to the latest source from the repo

**Comment by SomeKindofGamer** [comment]
> update to the latest source from the repo

I have

**Comment by isakube** [comment]
then I don't know

**Comment by puyoxyz** [comment]
(copy-pasted)

please use `git clone https://github.com/KadeDev/Kade-Engine.git` to clone the source code (instead of downloading the zip). (If you are on Windows, download git [here](http://git-scm.com/). If you are on macOS, run `git` and macOS will install it for you. If you are on Linux, install it with your package manager)

Also, download the latest source code, not 1.4.2's source code. (the clone command above does that for you). 1.4.2 is very outdated right now.

Reopen if bug still happens on **latest source code, cloned using `git` and not downloading the zip from GitHub's website**
