### ISSUE TITLE
Bug Report: Pico crashes the game

### ISSUE THREAD

**Issue by ghost** [KadeArchive/Kade-Engine#790]
Platform: Windows x64, newest source code update

If you decide to play pico songs, this happens
![obraz](https://user-images.githubusercontent.com/65465165/121195143-a465eb80-c86f-11eb-9b1a-e70200c335f7.png)

**Comment by ghost** [comment]
I should also mention, that other songs _**work perfecty fine**_

**Comment by Lucky-56** [comment]
does this only happen on 'Philly Nice' or any other songs?
if so, it's fixed in master

**Comment by Lucky-56** [comment]
assuming this happens on 'Philly Nice', **fixed in master**

how to fix if you know how to compile:
1. download [master-branch](https://github.com/KadeDev/Kade-Engine/tree/master) source code
2. compile using the steps of [their website](https://kadedev.github.io/Kade-Engine/building) (assuming you're on windows `lime build windows -final`)
3. then head into `export/final/bin` and there you have your self compiled `Kade Engine.exe`

**Comment by puyoxyz** [comment]
assuming this is related to #789

if it still happens on `master` (or 1.5.2 when that's out) then make a new issue, and include console output
