### ISSUE TITLE
Bug Report: Dad Battle crashes in story mode

### ISSUE THREAD

**Issue by fizzybombzz** [KadeArchive/Kade-Engine#796]
### If you are playing a downloaded version of the game, what operating system are you using?
Windows (`x86`), Windows (`x86_64`), Linux, or macOS? Specify below.

Windows (x64)

## What version of the game are you using? Look in the bottom left corner of the main menu.
1.5.1

**Comment by Lucky-56** [comment]
fixed in master

**Comment by Lucky-56** [comment]
wait a second, in dad battle?

**Comment by isakube** [comment]
DUPLICATE

seriously people read the templates. that and actually use them

**Comment by Lucky-56** [comment]
**fixed in master**

how to fix if you know how to compile:
1. download [master-branch](https://github.com/KadeDev/Kade-Engine/tree/master) source code
2. compile using the steps of [their website](https://kadedev.github.io/Kade-Engine/building) (assuming you're on windows `lime build windows -final`)
3. then head into `export/final/bin` and there you have your self compiled `Kade Engine.exe`
