### ISSUE TITLE
Bug Report: Songs with spaces broken

### ISSUE THREAD

**Issue by Scynette** [KadeArchive/Kade-Engine#804]
Well, this was a great engine. 1.5.1 fucked it up horribly. Simply put, any songs you decided to add spaces into (Dadbattle, Philly, and Winter-horrorland) all no longer work. To quote the error message, "**[lime.utils.Assets] ERROR: There is no TEXT asset with an ID of "assets/data/philly nice/philly nice-hard.json"**."  Unfortunantly, this means that weeks 1, 3, and 5 cannot be completed. Which is sad, I like Winter Horrorland. Satin Panties works just fine though, so that's nice? I hope you're working on 1.5.2

**Comment by isakube** [comment]
duplicate, known bug

**Comment by Lucky-56** [comment]
**fixed in master**

how to fix if you know how to compile:
1. download [master-branch](https://github.com/KadeDev/Kade-Engine/tree/master) source code
2. compile using the steps of [their website](https://kadedev.github.io/Kade-Engine/building) (assuming you're on windows `lime build windows -final`)
3. then head into `export/final/bin` and there you have your self compiled `Kade Engine.exe`

**Comment by puyoxyz** [comment]
I'm going to cry if there's one more issue about this.

**WE KNOW ABOUT IT**
