### ISSUE TITLE
"Missing" file 'assets/data/philly nice/philly nice-hard.json'

### ISSUE THREAD

**Issue by azabiphetamine** [KadeArchive/Kade-Engine#805]
![hol up whoat](https://user-images.githubusercontent.com/65814578/121399399-abb3f480-c956-11eb-981b-93b8e26b1ac5.png)

ok what
i have the files next to the error just to show that the files ARE there

edit: quick note i have duplicated the folder and now i have folders that are "philly" and "philly nice", with the files renamed as well, and this way it works in freeplay but still doesn't work in story mode

**Comment by isakube** [comment]
HOLY FUCK READ THE ISSUES BEFORE YOURS THIS HAS BEEN REPORTED 30 TIMES ALREADY

_ahem_ duplicate

**Comment by azabiphetamine** [comment]
i tried that you know

**Comment by Lucky-56** [comment]
how to fix if you know how to compile:
1. download [master-branch](https://github.com/KadeDev/Kade-Engine/tree/master) source code
2. compile using the steps of [their website](https://kadedev.github.io/Kade-Engine/building) (assuming you're on windows `lime build windows -final`)
3. then head into `export/final/bin` and there you have your self compiled `Kade Engine.exe`

_oh and yeah_ **fixed in master**

**Comment by puyoxyz** [comment]
i am officially crying
