### ISSUE TITLE
Can't build html5 because of extension-webm

### ISSUE THREAD

**Issue by Zer0PXL** [KadeArchive/Kade-Engine#963]
I'm trying to build a mod in html5, but in the newest version 1.5.3, it says I don't have extension-webm. I tried installing it, but I can't run 'lime rebuild extension-webm windows', when I do it says something about visual studio, which I don't have because I'm only compiling on html5. I tried to run 'lime rebuild extension-webm html5' but that doesn't do anything.

lime rebuild extension-webm windows output:
`C:\HaxeToolkit\haxe\lib\extension-webm\git\project>setlocal enabledelayedexpansion
Warning: Could not find environment variables for Visual Studio
Missing HXCPP_VARS
Error: Could not automatically setup MSVC`

lime test html5 -debug output:
`C:/HaxeToolkit/haxe/lib/extension-webm/git/webm/WebmPlayer.hx:3: characters 8-15 : You cannot access the cpp package while targeting js (for cpp.Lib)
source/Main.hx:4: characters 8-23 :     referenced here
export/debug/html5/haxe/ApplicationMain.hx:299: characters 48-52 :     referenced here`

**Comment by Zer0PXL** [comment]
Installed VS2019 and now it only gives me the error for lime test html5 -debug.

**Comment by ghost** [comment]
afaik, extension-webm uses native libraries and codecs from libvpx, which is only available on Windows, Mac, and Linux.

extension-webm is needed to play .webm files on desktop. HTML5 already has this capability without the extension, because it can just use the browser codec.

My proposed solution is to add some platform specific compiler conditionals to decide what to do with the webm, and play it accordingly.

**Comment by Kade-github** [comment]
fixed
